language: php

php:
  - '7.2'
  - '7.3'

dist: trusty

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction

script:
  - |
    vendor/bin/codecept build
    vendor/bin/codecept run --coverage-xml

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.3' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
    fi
